/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Your connection to a Grafeo database. */
export declare class GrafeoDB {
  /** Create a database. Pass a path for persistence, or omit for in-memory. */
  static create(path?: string | undefined | null): GrafeoDB
  /** Open an existing database at the given path. */
  static open(path: string): GrafeoDB
  /**
   * Open an existing database in read-only mode.
   *
   * Uses a shared file lock, so multiple processes can read the same
   * .grafeo file concurrently. Mutations will throw an error.
   */
  static openReadOnly(path: string): GrafeoDB
  /** Execute a GQL query. Returns a Promise<QueryResult>. */
  execute(query: string, params?: any | undefined | null): Promise<QueryResult>
  /**
   * Runs a read-only GQL query and returns an async cursor.
   *
   * The returned `ResultStream` yields one row at a time via `await
   * stream.next()`. Memory stays bounded regardless of result-set size.
   *
   * Rejects mutations (INSERT / DELETE / SET), EXPLAIN / PROFILE,
   * SESSION / SCHEMA commands, and queries that require push-based
   * operators (ORDER BY, aggregate, DISTINCT). Use `execute()` for those.
   *
   * **Stability:** experimental. Parameterized streaming queries are not
   * yet supported.
   */
  executeStream(query: string): Promise<JsResultStream>
  /** Create a node with labels and optional properties. */
  createNode(labels: Array<string>, properties?: object | undefined | null): JsNode
  /** Create an edge between two nodes. */
  createEdge(sourceId: number, targetId: number, edgeType: string, properties?: object | undefined | null): JsEdge
  /** Get a node by ID. */
  getNode(id: number): JsNode | null
  /** Get an edge by ID. */
  getEdge(id: number): JsEdge | null
  /** Delete a node by ID. Returns true if the node existed. */
  deleteNode(id: number): boolean
  /** Delete an edge by ID. Returns true if the edge existed. */
  deleteEdge(id: number): boolean
  /** Set a property on a node. */
  setNodeProperty(id: number, key: string, value: unknown): void
  /** Set a property on an edge. */
  setEdgeProperty(id: number, key: string, value: unknown): void
  /** Get the number of nodes. */
  nodeCount(): number
  /** Get the number of edges. */
  edgeCount(): number
  /**
   * Begin a transaction with an optional isolation level.
   *
   * Isolation levels: "read_committed", "snapshot" (default), "serializable".
   */
  beginTransaction(isolationLevel?: string | undefined | null): Transaction
  /** Create a vector similarity index on a node property. */
  createVectorIndex(label: string, property: string, dimensions?: number | undefined | null, metric?: string | undefined | null, m?: number | undefined | null, efConstruction?: number | undefined | null, quantization?: string | undefined | null): Promise<void>
  /**
   * Search for the k nearest neighbors of a query vector.
   *
   * Returns an array of [nodeId, distance] pairs sorted by distance
   * ascending (lower = more similar). The distance scale depends on
   * the metric configured at index creation.
   */
  vectorSearch(label: string, property: string, query: Array<number>, k: number, ef?: number | undefined | null, filters?: Record<string, any> | undefined | null): Promise<Array<Array<number>>>
  /** Bulk-insert nodes with vector properties. */
  batchCreateNodes(label: string, property: string, vectors: Array<Array<number>>): Promise<Array<number>>
  /** Remove a property from a node. Returns true if the property existed. */
  removeNodeProperty(id: number, key: string): boolean
  /** Remove a property from an edge. Returns true if the property existed. */
  removeEdgeProperty(id: number, key: string): boolean
  /** Add a label to an existing node. Returns true if the label was added. */
  addNodeLabel(id: number, label: string): boolean
  /** Remove a label from a node. Returns true if the label was removed. */
  removeNodeLabel(id: number, label: string): boolean
  /** Get all labels for a node. Returns null if the node doesn't exist. */
  getNodeLabels(id: number): Array<string> | null
  /** Returns high-level database information as a JSON object. */
  info(): any
  /** Returns schema information (labels, edge types, property keys) as a JSON object. */
  schema(): any
  /** Returns the Grafeo engine version string. */
  version(): string
  /**
   * Clear all cached query plans.
   *
   * Forces re-parsing and re-optimization on next execution.
   * Called automatically after DDL operations, but can be invoked manually.
   */
  clearPlanCache(): void
  /**
   * Forces a WAL checkpoint.
   *
   * Flushes all pending WAL records to the main storage.
   */
  walCheckpoint(): void
  /**
   * Saves the database to a file path.
   *
   * If in-memory, creates a new persistent database at the given path.
   * If file-backed, creates a copy at the new path.
   * The original database remains unchanged.
   */
  save(path: string): void
  /** Create a full backup of the database. */
  backupFull(backupDir: string): void
  /** Create an incremental backup (WAL records since last backup). */
  backupIncremental(backupDir: string): void
  /** Restore a database to a specific epoch from a backup chain. */
  static restoreToEpoch(backupDir: string, epoch: number, outputPath: string): void
  /** Close the database. */
  close(): void
  /**
   * Sets the current schema for subsequent `execute()` calls.
   *
   * Equivalent to running `SESSION SET SCHEMA <name>` but persists across
   * calls. Use `resetSchema()` to clear it.
   */
  setSchema(name: string): void
  /**
   * Clears the current schema context.
   *
   * Subsequent `execute()` calls will use the default (no-schema) namespace.
   */
  resetSchema(): void
  /** Returns the current schema name, or `null` if no schema is set. */
  currentSchema(): string | null
  /**
   * Creates a named graph projection. Returns `true` if created, `false`
   * if a projection with that name already exists.
   *
   * A projection is a read-only, filtered view of the default graph.
   * Only nodes with matching labels and edges with matching types are visible.
   */
  createProjection(name: string, nodeLabels?: Array<string> | undefined | null, edgeTypes?: Array<string> | undefined | null): boolean
  /** Drops a named graph projection. Returns `true` if it existed. */
  dropProjection(name: string): boolean
  /** Returns the names of all graph projections. */
  listProjections(): Array<string>
  /**
   * Drop a vector index for the given label and property.
   * Returns true if the index existed and was removed.
   */
  dropVectorIndex(label: string, property: string): Promise<boolean>
  /**
   * Rebuild a vector index by rescanning all matching nodes.
   * Preserves the original index configuration.
   *
   * Note: Vector indexes auto-sync when you call setNodeProperty(),
   * batchCreateNodes(), or batchCreateNodesWithProps() with vector data.
   * You only need this after non-standard data imports or to compact
   * the index after many deletions.
   */
  rebuildVectorIndex(label: string, property: string): Promise<void>
  /** Batch search for nearest neighbors of multiple query vectors. */
  batchVectorSearch(label: string, property: string, queries: Array<Array<number>>, k: number, ef?: number | undefined | null, filters?: Record<string, any> | undefined | null): Promise<Array<Array<Array<number>>>>
  /**
   * Search for diverse nearest neighbors using Maximal Marginal Relevance (MMR).
   *
   * Returns an array of [nodeId, distance] pairs in MMR selection order.
   * The distance values match vectorSearch() for the same nodes
   * (lower = more similar). The ordering reflects relevance-diversity
   * balance, not distance sorting.
   */
  mmrSearch(label: string, property: string, query: Array<number>, k: number, fetchK?: number | undefined | null, lambdaMult?: number | undefined | null, ef?: number | undefined | null, filters?: Record<string, any> | undefined | null): Promise<Array<Array<number>>>
  /**
   * Create a BM25 text index on a node property for full-text search.
   *
   * The index is automatically kept in sync as nodes are created,
   * updated, or deleted. You do not need to call rebuildTextIndex()
   * after normal write operations.
   */
  createTextIndex(label: string, property: string): Promise<void>
  /** Drop a text index for the given label and property. */
  dropTextIndex(label: string, property: string): Promise<boolean>
  /**
   * Rebuild a text index by rescanning all matching nodes.
   *
   * Note: Text indexes auto-sync on normal writes. You only need this
   * after importing data through non-standard paths.
   */
  rebuildTextIndex(label: string, property: string): Promise<void>
  /**
   * Search a text index using BM25 scoring.
   *
   * Returns an array of [nodeId, score] pairs sorted by descending
   * relevance (higher score = more relevant). BM25 scores are
   * unbounded positive floats.
   */
  textSearch(label: string, property: string, query: string, k: number): Promise<Array<Array<number>>>
  /**
   * Perform hybrid search combining text (BM25) and vector similarity.
   *
   * Requires both a text index (createTextIndex) and a vector index
   * (createVectorIndex). If either is missing, that source is silently
   * omitted from fusion.
   *
   * Returns an array of [nodeId, score] pairs sorted by fused score
   * descending (higher = more relevant). These are fusion scores,
   * NOT distances.
   */
  hybridSearch(label: string, textProperty: string, vectorProperty: string, queryText: string, k: number, queryVector?: Array<number> | undefined | null, fusion?: string | undefined | null, weights?: Array<number> | undefined | null): Promise<Array<Array<number>>>
  /**
   * Converts the database to a read-only CompactStore for faster queries.
   *
   * Takes a snapshot of all nodes and edges, builds a columnar store with
   * CSR adjacency, and switches to read-only mode. After this call, write
   * operations will fail.
   */
  compact(): void
  /** Enable CDC for all future sessions. */
  enableCdc(): void
  /** Disable CDC for all future sessions. */
  disableCdc(): void
  /** Returns whether CDC is currently enabled for new sessions. */
  get isCdcEnabled(): boolean
  /** Returns the full change history for a node. */
  nodeHistory(nodeId: number): Promise<Array<any>>
  /** Returns the full change history for an edge. */
  edgeHistory(edgeId: number): Promise<Array<any>>
  /** Returns change events for a node since a given epoch. */
  nodeHistorySince(nodeId: number, sinceEpoch: number): Promise<Array<any>>
  /** Returns all change events across entities in an epoch range. */
  changesBetween(startEpoch: number, endEpoch: number): Promise<Array<any>>
  /**
   * Import a CSV file as graph nodes.
   *
   * Each row becomes a node with the given label. Column headers are used
   * as property names. Returns the number of nodes created.
   */
  importCsv(path: string, options?: CsvImportOptions | undefined | null): Promise<number>
  /**
   * Import a JSON Lines file as graph nodes.
   *
   * Each line must be a valid JSON object. Object keys become property names.
   * Returns the number of nodes created.
   */
  importJsonl(path: string, options?: JsonlImportOptions | undefined | null): Promise<number>
}
export type JsGrafeoDB = GrafeoDB

/** An edge (relationship) between two nodes with a type and properties. */
export declare class JsEdge {
  /** Get the edge ID. */
  get id(): number
  /** Get the edge type (relationship type). */
  get edgeType(): string
  /** Get the source node ID. */
  get sourceId(): number
  /** Get the target node ID. */
  get targetId(): number
  /** Get a property value by key. */
  get(key: string): unknown
  /** Get all properties as a plain object. */
  properties(): object
  /** String representation. */
  toString(): string
}

/** A node in the graph with labels and properties. */
export declare class JsNode {
  /** Get the node ID. */
  get id(): number
  /** Get the node labels. */
  get labels(): Array<string>
  /** Get a property value by key. */
  get(key: string): unknown
  /** Get all properties as a plain object. */
  properties(): object
  /** Check if the node has a specific label. */
  hasLabel(label: string): boolean
  /** String representation. */
  toString(): string
}

/** Results from a query - access rows, nodes, and edges. */
export declare class QueryResult {
  /** Get column names. */
  get columns(): Array<string>
  /** Get number of rows. */
  get length(): number
  /** Query execution time in milliseconds (if available). */
  get executionTimeMs(): number | null
  /** Number of rows scanned during execution (if available). */
  get rowsScanned(): number | null
  /** Get a single row by index as a plain object. */
  get(index: number): object
  /** Get all rows as an array of objects. */
  toArray(): Array<object>
  /** Get first column of first row (single value). */
  scalar(): unknown
  /** Get nodes found in the result. */
  nodes(): Array<JsNode>
  /** Get edges found in the result. */
  edges(): Array<JsEdge>
  /** Returns the result formatted as a Unicode table. */
  toString(): string
  /**
   * Returns the result as Arrow IPC stream bytes (Buffer).
   *
   * Use with the `apache-arrow` npm package:
   * ```js
   * import { tableFromIPC } from 'apache-arrow';
   * const table = tableFromIPC(result.toArrowIPC());
   * ```
   */
  toArrowIPC(): Buffer
  /** Get all rows as an array of arrays (no column names). */
  rows(): object
}

/**
 * Async cursor over the rows of a lazy GQL query.
 *
 * Obtained from [`GrafeoDB.executeStream()`](super::database::JsGrafeoDB::execute_stream).
 * Holds bounded memory regardless of result size (one chunk at a time).
 *
 * # Stability: Experimental
 */
export declare class ResultStream {
  /** Column names in the order they appear in each row object. */
  get columns(): Array<string>
  /**
   * Pulls the next row as a plain object, or `null` when the stream is
   * exhausted. Runs the Rust work on a blocking thread so the Node.js
   * event loop stays responsive.
   *
   * Values follow the Grafeo JSON convention: strings, numbers, booleans,
   * and `null` map directly; temporal and complex types use the tagged
   * form documented in `grafeo-bindings-common::json` (e.g. `{ "$date": ... }`).
   */
  next(): Promise<JsonValue | null>
  /**
   * Explicitly releases the underlying operator tree. After calling this,
   * `next()` returns `null`. Useful when you want to break out of iteration
   * early without waiting for GC.
   */
  close(): void
}
export type JsResultStream = ResultStream

/**
 * A database transaction with explicit commit/rollback.
 *
 * In Node.js 22+, use with `using` for automatic cleanup:
 * ```js
 * using tx = db.beginTransaction();
 * await tx.execute("INSERT (:Person {name: 'Alix'})");
 * tx.commit();
 * // auto-rollback if commit not called
 * ```
 */
export declare class Transaction {
  /** Execute a GQL query within this transaction. */
  execute(query: string, params?: any | undefined | null): Promise<QueryResult>
  /** Commit the transaction. */
  commit(): void
  /** Roll back the transaction. */
  rollback(): void
  /** Whether the transaction is still active. */
  get isActive(): boolean
}

/** Options for CSV import. */
export interface CsvImportOptions {
  /** Label to assign to created nodes (default: "Row") */
  label?: string
  /** Whether the first row contains headers (default: true) */
  headers?: boolean
}

/** Options for JSON Lines import. */
export interface JsonlImportOptions {
  /** Label to assign to created nodes (default: "Row") */
  label?: string
}

/** Returns the active SIMD instruction set for vector operations. */
export declare function simdSupport(): string

/** Returns the Grafeo version. */
export declare function version(): string
